# Generated by Django 4.2 on 2023-04-17 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_product_wishlist_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
