# Generated by Django 5.2.2 on 2025-10-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_address_ordereditems'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='landmark',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
