# Generated by Django 5.2.2 on 2025-11-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_paymentrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='total_amount',
            field=models.CharField(max_length=100),
        ),
    ]
