# Generated by Django 5.2.2 on 2025-11-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_alter_paymentrecord_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bought_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
